PatientCarePlan/Controllers/AuthAuthController.cs
using PatientCarePlan.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace PatientCarePlan.Controllers
{
    [AllowAnonymous]
    public class AuthAuthController : Controller
    {
        // GET: AuthAuth
        [AllowAnonymous]
        public ActionResult Login()
        {
            return View();
        }

        [AllowAnonymous]
        [HttpPost]
        public ActionResult Login(User user)
        {
            //access your database, get user with the username and password
            PatientCarePlanContext db = new PatientCarePlanContext();
            int count = db.Users.Where(x => x.UserName == user.UserName
                        && x.password == user.password).Count();

            if (count == 0)
            {
                ViewBag.errMsg = "No Match Found";
                return View();
            }
            else
            {
                FormsAuthentication.SetAuthCookie(user.UserName, false);
                return RedirectToAction("Index", "Home");
            }
        }

        public ActionResult Logout()
        {
            //signout/logout
            FormsAuthentication.SignOut();
            return RedirectToAction("Index", "Home");
        }
        //return View();
    }
}

PatientCarePlan/Views/AuthAuth/Login.cshtml
@model PatientCarePlan.Models.User

<h1>LogIn</h1>
<h3>@ViewBag.errMsg</h3>
@using (Html.BeginForm("Login", "AuthAuth", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <h4>User</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.password, "", new { @class = "text-danger" })
            </div>
        </div>



        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Login" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>